# Generated by Django 3.2.7 on 2022-10-21 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_person_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='slug',
        ),
    ]
