# Generated by Django 3.2.7 on 2022-11-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_remove_movie_watch_list'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='watch_list',
            field=models.ManyToManyField(blank=True, to='movies.Movie'),
        ),
    ]
