# Generated by Django 3.2.7 on 2022-10-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_person_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_cover',
            field=models.FileField(default='', upload_to='images/covers'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image_name',
            field=models.FileField(default='', upload_to='images/afişler'),
        ),
    ]
