# Generated by Django 3.2.7 on 2022-10-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movie_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='image_name',
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.FileField(default='', upload_to='images/cast'),
        ),
    ]
