# Generated by Django 3.2.7 on 2022-11-07 06:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0013_comment_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watch_list',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
