# Generated by Django 3.2.7 on 2022-11-07 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_movie_watch_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='watch_list',
        ),
    ]
